package org.jdesktop.lg3d.apps.remoteviewer.viewer.main;

import com.protonmail.landrevillejf.IconManager;
import org.jdesktop.lg3d.apps.remoteviewer.AboutGUI;
import org.jdesktop.lg3d.apps.remoteviewer.Main;
import org.jdesktop.lg3d.apps.remoteviewer.SysTray;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Hashtable;
import java.util.zip.Deflater;

/**
 * ViewerGUI.java
 * @author  benbac
 */

public class ViewerGUI extends JFrame {

    private final byte COLOR_FULL = 0;
    private final byte COLOR_16_BIT = 1;
    private final byte COLOR_256 = 2;
    private final byte COLOR_GRAY = 3;

    private boolean fullScreenMode = false;

    private Recorder recorder;

    /** Creates new form MainFrame */
    public ViewerGUI(Recorder recorder) {
        this.recorder = recorder;
        initComponents();
        jScrollPane1.setViewportView(recorder.screenPlayer);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public void Start() {
        jBtnStartStopActionPerformed(null);
    }

    // Helper method to safely get Image from Icon
    private Image getImageFromIcon(Icon icon) {
        if (icon instanceof ImageIcon) {
            return ((ImageIcon) icon).getImage();
        }
        // If not an ImageIcon, create a BufferedImage from the Icon
        BufferedImage image = new BufferedImage(
                icon.getIconWidth(),
                icon.getIconHeight(),
                BufferedImage.TYPE_INT_ARGB
        );
        Graphics2D g2d = image.createGraphics();
        icon.paintIcon(null, g2d, 0, 0);
        g2d.dispose();
        return image;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jPopupMenuFileTranfer = new JPopupMenu();
        jMenuItemSendFiles = new JMenuItem();
        jMenuItemReceiveFiles = new JMenuItem();
        jToolBar1 = new JToolBar();
        jBtnStartStop = new JButton();
        jToggleBtnPauseResume = new JToggleButton();
        jBtnViewCtrl = new JButton();
        jSeparator1 = new JToolBar.Separator();
        jBtnFullNormal = new JButton();
        jBtnPartialComplete = new JButton();
        jSeparator9 = new JToolBar.Separator();
        jLabel2 = new JLabel();
        jComboBoxSc = new JComboBox<>();
        jSeparator7 = new JToolBar.Separator();
        jLabel3 = new JLabel();
        jCheckBoxDC = new JCheckBox();
        jComboBoxCL = new JComboBox<>();
        jSeparator4 = new JToolBar.Separator();
        jLabel4 = new JLabel();
        jCheckBoxCQ = new JCheckBox();
        jSlider1 = new JSlider();
        jSeparator11 = new JToolBar.Separator();
        jLabel1 = new JLabel();
        jComboBoxColorQuality = new JComboBox<>();
        jSeparator5 = new JToolBar.Separator();
        jLabel5 = new JLabel();
        jCheckBoxClipTrans = new JCheckBox();
        jBtnFileTransfer = new JButton();
        jSeparator6 = new JToolBar.Separator();
        jBtnConnectionInfos = new JButton();
        jBtnServerProps = new JButton();
        jSeparator12 = new JToolBar.Separator();
        jBtnAbout = new JButton();
        jBtnClose = new JButton();
        jSeparator10 = new JToolBar.Separator();
        jScrollPane1 = new JScrollPane();

        jMenuItemSendFiles.setText("Send files");
        jMenuItemSendFiles.addActionListener(evt -> jMenuItemSendFilesActionPerformed(evt));
        jPopupMenuFileTranfer.add(jMenuItemSendFiles);

        jMenuItemReceiveFiles.setText("Receive files");
        jMenuItemReceiveFiles.addActionListener(evt -> jMenuItemReceiveFilesActionPerformed(evt));
        jPopupMenuFileTranfer.add(jMenuItemReceiveFiles);

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(" Remote Viewer");

        // Set icon using IconManager
        Icon pauseIcon = IconManager.loadIcon(IconManager.IconCategory.MEDIA, "Pause", 16, 16);
        setIconImage(getImageFromIcon(pauseIcon));

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setAlignmentY(0.5F);
        jToolBar1.setMaximumSize(new Dimension(713, 35));

        // All icons loaded through IconManager
        jBtnStartStop.setIcon(IconManager.loadIcon(IconManager.IconCategory.MEDIA, "Stop", 16, 16));
        jBtnStartStop.setToolTipText("Start/Stop recording");
        jBtnStartStop.setFocusable(false);
        jBtnStartStop.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnStartStop.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnStartStop.addActionListener(evt -> jBtnStartStopActionPerformed(evt));
        jToolBar1.add(jBtnStartStop);

        jToggleBtnPauseResume.setIcon(IconManager.loadIcon(IconManager.IconCategory.MEDIA, "Pause", 16, 16));
        jToggleBtnPauseResume.setToolTipText("Pause/Resume recording");
        jToggleBtnPauseResume.setFocusable(false);
        jToggleBtnPauseResume.addActionListener(evt -> jToggleBtnPauseResumeActionPerformed(evt));
        jToolBar1.add(jToggleBtnPauseResume);

        jBtnViewCtrl.setIcon(IconManager.loadIcon(IconManager.IconCategory.DEVELOPMENT, "Host", 16, 16));
        jBtnViewCtrl.setToolTipText("View only / Full control");
        jBtnViewCtrl.setFocusable(false);
        jBtnViewCtrl.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnViewCtrl.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnViewCtrl.addActionListener(evt -> jBtnViewCtrlActionPerformed(evt));
        jToolBar1.add(jBtnViewCtrl);
        jToolBar1.add(jSeparator1);

        jBtnFullNormal.setIcon(IconManager.loadIcon(IconManager.IconCategory.DEVELOPMENT, "Host", 16, 16));
        jBtnFullNormal.setToolTipText("Full / Normal screen");
        jBtnFullNormal.setFocusable(false);
        jBtnFullNormal.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnFullNormal.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnFullNormal.addActionListener(evt -> jBtnFullNormalActionPerformed(evt));
        jToolBar1.add(jBtnFullNormal);

        jBtnPartialComplete.setIcon(IconManager.loadIcon(IconManager.IconCategory.DEVELOPMENT, "Host", 16, 16));
        jBtnPartialComplete.setToolTipText("Custom / Default screen");
        jBtnPartialComplete.setFocusable(false);
        jBtnPartialComplete.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnPartialComplete.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnPartialComplete.addActionListener(evt -> jBtnPartialCompleteActionPerformed(evt));
        jToolBar1.add(jBtnPartialComplete);
        jToolBar1.add(jSeparator9);

        jLabel2.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "Preferences", 16, 16));
        jLabel2.setText(" ");
        jLabel2.setToolTipText("Screen scale ");
        jLabel2.setFocusable(false);
        jToolBar1.add(jLabel2);

        jComboBoxSc.setModel(new DefaultComboBoxModel<>(new String[] { "25", "50", "75", "100", "125", "150", "200" }));
        jComboBoxSc.setSelectedIndex(3);
        jComboBoxSc.setFocusable(false);
        jComboBoxSc.setMaximumSize(new Dimension(50, 20));
        jComboBoxSc.setMinimumSize(new Dimension(50, 20));
        jComboBoxSc.setPreferredSize(new Dimension(50, 20));
        jComboBoxSc.addItemListener(evt -> jComboBoxScItemStateChanged(evt));
        jToolBar1.add(jComboBoxSc);
        jToolBar1.add(jSeparator7);

        jLabel3.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "Preferences", 16, 16));
        jLabel3.setToolTipText("Enable/Disable Data compression");
        jLabel3.setFocusable(false);
        jToolBar1.add(jLabel3);

        jCheckBoxDC.setSelected(true);
        jCheckBoxDC.setToolTipText("Enable/Disable Data compression");
        jCheckBoxDC.setFocusable(false);
        jCheckBoxDC.setHorizontalAlignment(SwingConstants.TRAILING);
        jCheckBoxDC.setHorizontalTextPosition(SwingConstants.LEFT);
        jCheckBoxDC.setVerticalTextPosition(SwingConstants.BOTTOM);
        jCheckBoxDC.addActionListener(evt -> jCheckBoxDCActionPerformed(evt));
        jToolBar1.add(jCheckBoxDC);

        jComboBoxCL.setModel(new DefaultComboBoxModel<>(new String[] { "Best", "Fastest", "Default", "Deflated", "Filtered", "Huffman", "Store" }));
        jComboBoxCL.setFocusable(false);
        jComboBoxCL.setMaximumSize(new Dimension(80, 20));
        jComboBoxCL.setMinimumSize(new Dimension(80, 20));
        jComboBoxCL.setPreferredSize(new Dimension(80, 20));
        jComboBoxCL.addItemListener(evt -> jComboBoxCLItemStateChanged(evt));
        jToolBar1.add(jComboBoxCL);
        jToolBar1.add(jSeparator4);

        jLabel4.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "Preferences", 16, 16));
        jLabel4.setToolTipText("Enable/Disable JPEG quality compression");
        jLabel4.setFocusable(false);
        jToolBar1.add(jLabel4);

        jCheckBoxCQ.setSelected(true);
        jCheckBoxCQ.setToolTipText("Enable/Disable JPEG quality compression");
        jCheckBoxCQ.setFocusable(false);
        jCheckBoxCQ.setHorizontalTextPosition(SwingConstants.LEFT);
        jCheckBoxCQ.setVerticalTextPosition(SwingConstants.BOTTOM);
        jCheckBoxCQ.addActionListener(evt -> jCheckBoxCQActionPerformed(evt));
        jToolBar1.add(jCheckBoxCQ);

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(10);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(7);
        jSlider1.setFocusable(false);
        jSlider1.setMaximumSize(new Dimension(100, 33));
        jSlider1.setMinimumSize(new Dimension(100, 33));
        jSlider1.setPreferredSize(new Dimension(100, 33));
        jSlider1.addChangeListener(evt -> jSlider1StateChanged(evt));
        jToolBar1.add(jSlider1);
        jToolBar1.add(jSeparator11);

        jLabel1.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "Preferences", 16, 16));
        jLabel1.setText(" ");
        jLabel1.setToolTipText("Color quality");
        jLabel1.setFocusable(false);
        jToolBar1.add(jLabel1);

        jComboBoxColorQuality.setModel(new DefaultComboBoxModel<>(new String[] { "Full colors", "16 bit colors", "256 colors", "Gray color" }));
        jComboBoxColorQuality.setFocusable(false);
        jComboBoxColorQuality.setLightWeightPopupEnabled(false);
        jComboBoxColorQuality.setMaximumSize(new Dimension(100, 20));
        jComboBoxColorQuality.setMinimumSize(new Dimension(100, 20));
        jComboBoxColorQuality.setPreferredSize(new Dimension(100, 20));
        jComboBoxColorQuality.addItemListener(evt -> jComboBoxColorQualityItemStateChanged(evt));
        jToolBar1.add(jComboBoxColorQuality);
        jToolBar1.add(jSeparator5);

        jLabel5.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "Preferences", 16, 16));
        jLabel5.setToolTipText("Enable/Disable Clipboard transfer");
        jLabel5.setFocusable(false);
        jToolBar1.add(jLabel5);

        jCheckBoxClipTrans.setSelected(true);
        jCheckBoxClipTrans.setToolTipText("Enable/Disable Clipboard transfer");
        jCheckBoxClipTrans.setFocusable(false);
        jCheckBoxClipTrans.setHorizontalTextPosition(SwingConstants.LEFT);
        jCheckBoxClipTrans.setVerticalTextPosition(SwingConstants.BOTTOM);
        jCheckBoxClipTrans.addActionListener(evt -> jCheckBoxClipTransActionPerformed(evt));
        jToolBar1.add(jCheckBoxClipTrans);

        jBtnFileTransfer.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "Preferences", 16, 16));
        jBtnFileTransfer.setToolTipText("File transfer");
        jBtnFileTransfer.setFocusable(false);
        jBtnFileTransfer.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnFileTransfer.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnFileTransfer.addActionListener(evt -> jBtnFileTransferActionPerformed(evt));
        jToolBar1.add(jBtnFileTransfer);
        jToolBar1.add(jSeparator6);

        jBtnConnectionInfos.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "About", 16, 16));
        jBtnConnectionInfos.setToolTipText("Connection infos");
        jBtnConnectionInfos.setFocusable(false);
        jBtnConnectionInfos.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnConnectionInfos.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnConnectionInfos.addActionListener(evt -> jBtnConnectionInfosActionPerformed(evt));
        jToolBar1.add(jBtnConnectionInfos);

        jBtnServerProps.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "Preferences", 16, 16));
        jBtnServerProps.setToolTipText("Server properties");
        jBtnServerProps.setFocusable(false);
        jBtnServerProps.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnServerProps.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnServerProps.addActionListener(evt -> jBtnServerPropsActionPerformed(evt));
        jToolBar1.add(jBtnServerProps);
        jToolBar1.add(jSeparator12);

        jBtnAbout.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "About", 16, 16));
        jBtnAbout.setToolTipText("About Remote Viewer");
        jBtnAbout.setFocusable(false);
        jBtnAbout.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnAbout.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnAbout.addActionListener(evt -> jBtnAboutActionPerformed(evt));
        jToolBar1.add(jBtnAbout);

        jBtnClose.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "Stop", 16, 16));
        jBtnClose.setToolTipText("Exit viewer");
        jBtnClose.setFocusable(false);
        jBtnClose.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnClose.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtnClose.addActionListener(evt -> jBtnCloseActionPerformed(evt));
        jToolBar1.add(jBtnClose);
        jToolBar1.add(jSeparator10);

        jScrollPane1.setFocusable(false);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jToolBar1, GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jToolBar1, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
        );
    }

    private void jBtnStartStopActionPerformed(java.awt.event.ActionEvent evt) {
        if (recorder.isRecording())
            recorder.Stop();
        else
            recorder.Start();

        if (recorder.isRecording()) {
            Icon hostIcon = IconManager.loadIcon(IconManager.IconCategory.DEVELOPMENT, "Host", 16, 16);
            setIconImage(getImageFromIcon(hostIcon));

            Icon stopIcon = IconManager.loadIcon(IconManager.IconCategory.MEDIA, "Stop", 16, 16);
            jBtnStartStop.setIcon(stopIcon);

            setTitle("Remote Viewer [" + Config.server_address + "]");
        } else {
            setTitle("Remote Viewer");

            Icon resumeIcon = IconManager.loadIcon(IconManager.IconCategory.MEDIA, "Resume", 16, 16);
            setIconImage(getImageFromIcon(resumeIcon));

            Icon playIcon = IconManager.loadIcon(IconManager.IconCategory.MEDIA, "Play", 16, 16);
            jBtnStartStop.setIcon(playIcon);

            jToggleBtnPauseResume.setSelected(false);

            jBtnViewCtrl.setIcon(IconManager.loadIcon(IconManager.IconCategory.MEDIA, "Play", 16, 16));

            Icon hostIcon = IconManager.loadIcon(IconManager.IconCategory.DEVELOPMENT, "Host", 16, 16);
            jBtnFullNormal.setIcon(hostIcon);
            jBtnPartialComplete.setIcon(hostIcon);
        }
    }

    private void jBtnViewCtrlActionPerformed(java.awt.event.ActionEvent evt) {
        recorder.setViewOnly(!recorder.isViewOnly());
        Icon icon = IconManager.loadIcon(IconManager.IconCategory.MEDIA, "Play", 16, 16);
        jBtnViewCtrl.setIcon(icon);
    }

    private void jBtnFullNormalActionPerformed(java.awt.event.ActionEvent evt) {
        changeFullScreenMode();
    }

    private void jBtnPartialCompleteActionPerformed(java.awt.event.ActionEvent evt) {
        if (recorder.isRecording()) {
            if (recorder.screenPlayer.isPartialScreenMode()) {
                Icon hostIcon = IconManager.loadIcon(IconManager.IconCategory.DEVELOPMENT, "Host", 16, 16);
                jBtnPartialComplete.setIcon(hostIcon);
                recorder.screenPlayer.stopSelectingMode();
            } else {
                recorder.screenPlayer.startSelectingMode();
            }
        }
    }

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {
        if (jSlider1.getValueIsAdjusting()) {
            recorder.viewerData.setCompressionQuality((float)jSlider1.getValue() / 10.0f);
            if (recorder.isRecording()) recorder.viewer.updateOptions();
        }
    }

    private void jCheckBoxCQActionPerformed(java.awt.event.ActionEvent evt) {
        jSlider1.setEnabled(jCheckBoxCQ.isSelected());
        if (!jCheckBoxCQ.isSelected())
            recorder.viewerData.setCompressionQuality(-1);
        else
            recorder.viewerData.setCompressionQuality((float)jSlider1.getValue() / 10.0f);
        if (recorder.isRecording()) recorder.viewer.updateOptions();
    }

    private void jBtnAboutActionPerformed(java.awt.event.ActionEvent evt) {
        AboutGUI.main(null);
    }

    private void jComboBoxColorQualityItemStateChanged(java.awt.event.ItemEvent evt) {
        setColorQuality(jComboBoxColorQuality.getSelectedIndex());
    }

    private void formWindowClosing(WindowEvent evt) {
        if (evt.getID() == WindowEvent.WINDOW_CLOSING)
            jBtnCloseActionPerformed(null);
        else
            super.processWindowEvent(evt);
    }

    private void jCheckBoxDCActionPerformed(java.awt.event.ActionEvent evt) {
        jComboBoxCL.setEnabled(jCheckBoxDC.isSelected());
        recorder.viewerData.setDataCompression(jCheckBoxDC.isSelected());
        if (recorder.isRecording()) recorder.viewer.updateOptions();
    }

    private void jComboBoxScItemStateChanged(java.awt.event.ItemEvent evt) {
        recorder.viewerData.setScreenScale(
                Float.parseFloat(jComboBoxSc.getSelectedItem().toString()) / 100.0f);
        if (recorder.isRecording()) recorder.viewer.updateOptions();
    }

    private void jComboBoxCLItemStateChanged(java.awt.event.ItemEvent evt) {
        setCompressionLevel(jComboBoxCL.getSelectedIndex());
    }

    private void jCheckBoxClipTransActionPerformed(java.awt.event.ActionEvent evt) {
        setClipboardTransfer(jCheckBoxClipTrans.isSelected());
    }

    private void jBtnFileTransferActionPerformed(java.awt.event.ActionEvent evt) {
        jPopupMenuFileTranfer.show(jBtnFileTransfer, 15, 15);
    }

    private void jMenuItemSendFilesActionPerformed(java.awt.event.ActionEvent evt) {
        if (!recorder.isRecording()) return;
        File[] files = recorder.clipbrdUtility.getFilesFromClipboard();
        if (files.length == 0) {
            JOptionPane.showMessageDialog(ViewerGUI.this,
                    "No file in clipboard !!",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        recorder.fileManager.setFiles(files);
        recorder.viewer.AddObject(new File("."));
    }

    private void jMenuItemReceiveFilesActionPerformed(java.awt.event.ActionEvent evt) {
        if (!recorder.isRecording()) return;
        recorder.viewer.AddObject(new File(".."));
    }

    private void jBtnServerPropsActionPerformed(java.awt.event.ActionEvent evt) {
        if (!recorder.isRecording()) return;
        recorder.viewer.AddObject(new Hashtable<>(0));
    }

    private void jBtnConnectionInfosActionPerformed(java.awt.event.ActionEvent evt) {
        if (!recorder.isRecording()) return;
        recorder.connectionInfos.display();
    }

    private void jToggleBtnPauseResumeActionPerformed(java.awt.event.ActionEvent evt) {
        if (recorder.isRecording()) {
            recorder.setPause(!recorder.isPaused());
            if (recorder.isPaused())
                jToggleBtnPauseResume.setSelected(true);
            else
                jToggleBtnPauseResume.setSelected(false);
        }
    }

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {
        if (JOptionPane.showConfirmDialog(this, "Exit Viewer ?", "Confirm Dialog",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            if (recorder.isRecording())
                recorder.viewer.Stop();
            dispose();
        }
    }

    public boolean isFullScreenMode() {
        return fullScreenMode;
    }

    public void changeFullScreenMode() {
        GraphicsDevice device = getGraphicsConfiguration().getDevice();
        if (!device.isFullScreenSupported()) return;

        fullScreenMode = !fullScreenMode;

        if (fullScreenMode) {
            dispose();
            setUndecorated(true);
            device.setFullScreenWindow(this);
            setVisible(true);

            Icon aboutIcon = IconManager.loadIcon(IconManager.IconCategory.GENERAL, "About", 16, 16);
            jBtnFullNormal.setIcon(aboutIcon);
        } else {
            dispose();
            setUndecorated(false);
            device.setFullScreenWindow(null);
            setVisible(true);

            Icon hostIcon = IconManager.loadIcon(IconManager.IconCategory.DEVELOPMENT, "Host", 16, 16);
            jBtnFullNormal.setIcon(hostIcon);
        }
    }

    public void setColorQuality(int colorQuality) {
        switch (colorQuality) {
            case COLOR_FULL: colorQuality = BufferedImage.TYPE_INT_ARGB; break;
            case COLOR_16_BIT: colorQuality = BufferedImage.TYPE_USHORT_555_RGB; break;
            case COLOR_256: colorQuality = BufferedImage.TYPE_BYTE_INDEXED; break;
            case COLOR_GRAY: colorQuality = BufferedImage.TYPE_BYTE_GRAY; break;
        }
        recorder.viewerData.setColorQuality(colorQuality);
        if (recorder.isRecording()) recorder.viewer.updateOptions();
    }

    public void setCompressionLevel(int index) {
        int level = Deflater.DEFAULT_COMPRESSION;
        switch(index) {
            case 0: level = Deflater.BEST_COMPRESSION; break;
            case 1: level = Deflater.BEST_SPEED; break;
            case 2: level = Deflater.DEFAULT_COMPRESSION; break;
            case 3: level = Deflater.DEFLATED; break;
            case 4: level = Deflater.FILTERED; break;
            case 5: level = Deflater.HUFFMAN_ONLY; break;
            case 6: level = Deflater.NO_COMPRESSION; break;
        }
        recorder.viewerData.setCompressionLevel(level);
        if (recorder.isRecording()) recorder.viewer.updateOptions();
    }

    public void setClipboardTransfer(boolean bool) {
        recorder.viewerData.setClipboardTransfer(bool);
        if (bool)
            recorder.clipbrdUtility.addFlavorListener();
        else
            recorder.clipbrdUtility.removeFlavorListener();
        if (recorder.isRecording()) recorder.viewer.updateOptions();
    }

    // Variables declaration
    private JButton jBtnAbout;
    private JButton jBtnClose;
    private JButton jBtnConnectionInfos;
    private JButton jBtnFileTransfer;
    private JButton jBtnFullNormal;
    public JButton jBtnPartialComplete;
    private JButton jBtnServerProps;
    private JButton jBtnStartStop;
    private JButton jBtnViewCtrl;
    private JCheckBox jCheckBoxCQ;
    private JCheckBox jCheckBoxClipTrans;
    private JCheckBox jCheckBoxDC;
    private JComboBox<String> jComboBoxCL;
    private JComboBox<String> jComboBoxColorQuality;
    private JComboBox<String> jComboBoxSc;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JMenuItem jMenuItemReceiveFiles;
    private JMenuItem jMenuItemSendFiles;
    private JPopupMenu jPopupMenuFileTranfer;
    private JScrollPane jScrollPane1;
    private JToolBar.Separator jSeparator1;
    private JToolBar.Separator jSeparator10;
    private JToolBar.Separator jSeparator11;
    private JToolBar.Separator jSeparator12;
    private JToolBar.Separator jSeparator4;
    private JToolBar.Separator jSeparator5;
    private JToolBar.Separator jSeparator6;
    private JToolBar.Separator jSeparator7;
    private JToolBar.Separator jSeparator9;
    private JSlider jSlider1;
    private JToggleButton jToggleBtnPauseResume;
    private JToolBar jToolBar1;
}
