package org.jdesktop.lg3d.apps.remoteviewer;

import com.protonmail.landrevillejf.IconManager;
import org.jdesktop.lg3d.apps.remoteviewer.server.main.ActiveConnectionsGUI;
import org.jdesktop.lg3d.apps.remoteviewer.server.main.ConfigGUI;
import org.jdesktop.lg3d.apps.remoteviewer.server.rmi.Server;
import org.jdesktop.lg3d.apps.remoteviewer.viewer.main.ConnectionDialog;

import javax.swing.*;
import java.awt.*;

/**
 * The original jrdesktop/Remote Viewer main GUI (server controls, status,
 * viewer connect, about, exit), unchanged in content and layout from the
 * standalone application. Only the top-level container changed: it is hosted
 * as a {@link JPanel} inside a lg3d {@code Frame3D} via
 * {@link org.jdesktop.lg3d.apps.TitledSwingWindow} (see {@link RemoteViewer}),
 * the same pattern every other lg3d-apps Swing app uses, instead of owning its
 * own top-level {@code JFrame}. Every button, layout and action listener below
 * is the same as the original {@code MainFrame}.
 */
public class RemoteViewerPanel extends JPanel {

    /** Preferred width of the hosted panel, in pixels (the original's packed size). */
    public static final int WIDTH_PX = 480;
    /** Preferred height of the hosted panel, in pixels (the original's packed size). */
    public static final int HEIGHT_PX = 380;

    /** Creates new form ServerGUI */
    public RemoteViewerPanel() {
        initComponents();
        setPreferredSize(new Dimension(WIDTH_PX, HEIGHT_PX));
        updateStatus();

        Config.loadConfiguration();
        jCheckBoxWindow.setSelected(Config.GUI_disabled);
        jCheckBoxTrayicon.setSelected(Config.Systray_disabled);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jPopupMenuFileTranfer = new JPopupMenu();
        jMenuItemSendFiles = new JMenuItem();
        jMenuItemReceiveFiles = new JMenuItem();
        jPanel1 = new JPanel();
        jButtonStartStop = new JButton();
        jButtonFileTrans = new JButton();
        jButtonViewers = new JButton();
        jButtonConfig = new JButton();
        jScrollPane1 = new JScrollPane();
        jTextAreaStatus = new JTextArea();
        jCheckBoxWindow = new JCheckBox();
        jCheckBoxTrayicon = new JCheckBox();
        jPanel2 = new JPanel();
        jButton1 = new JButton();
        jButtonAbout = new JButton();
        jButtonExit = new JButton();

        jMenuItemSendFiles.setText("Send files");
        jMenuItemSendFiles.addActionListener(evt -> jMenuItemSendFilesActionPerformed(evt));
        jPopupMenuFileTranfer.add(jMenuItemSendFiles);

        jMenuItemReceiveFiles.setText("Receive files");
        jMenuItemReceiveFiles.addActionListener(evt -> jMenuItemReceiveFilesActionPerformed(evt));
        jPopupMenuFileTranfer.add(jMenuItemReceiveFiles);

        jPanel1.setBorder(BorderFactory.createTitledBorder("Server"));

        // All icons loaded through IconManager
        jButtonStartStop.setIcon(IconManager.loadIcon(IconManager.IconCategory.MEDIA, "Play", 16, 16));
        jButtonStartStop.setText("Start");
        jButtonStartStop.addActionListener(evt -> jButtonStartStopActionPerformed(evt));

        jButtonFileTrans.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "Preferences", 16, 16));
        jButtonFileTrans.setText("File transfer");
        jButtonFileTrans.addActionListener(evt -> jButtonFileTransActionPerformed(evt));

        jButtonViewers.setIcon(IconManager.loadIcon(IconManager.IconCategory.DEVELOPMENT, "Host", 16, 16));
        jButtonViewers.setText("Active connections...");
        jButtonViewers.addActionListener(evt -> jButtonViewersActionPerformed(evt));

        jButtonConfig.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "Preferences", 16, 16));
        jButtonConfig.setText("Configuration");
        jButtonConfig.addActionListener(evt -> jButtonConfigActionPerformed(evt));

        jTextAreaStatus.setColumns(20);
        jTextAreaStatus.setEditable(false);
        jTextAreaStatus.setFont(new Font("Courier New", 0, 12));
        jTextAreaStatus.setRows(4);
        jTextAreaStatus.setBorder(BorderFactory.createTitledBorder("Status"));
        jScrollPane1.setViewportView(jTextAreaStatus);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 213, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonFileTrans, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonViewers, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonConfig, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonStartStop, GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonStartStop)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonConfig)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonViewers)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonFileTrans))
                                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                .addContainerGap())
        );

        jCheckBoxWindow.setSelected(true);
        jCheckBoxWindow.setText("Do not display this window on application startup.");
        jCheckBoxWindow.addActionListener(evt -> jCheckBoxWindowActionPerformed(evt));

        jCheckBoxTrayicon.setSelected(true);
        jCheckBoxTrayicon.setText("Disable Trayicon.");
        jCheckBoxTrayicon.addActionListener(evt -> jCheckBoxTrayiconActionPerformed(evt));

        jPanel2.setBorder(BorderFactory.createTitledBorder(""));

        jButton1.setIcon(IconManager.loadIcon(IconManager.IconCategory.DEVELOPMENT, "Host", 16, 16));
        jButton1.setText("Connect to Server ...");
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));

        jButtonAbout.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "About", 16, 16));
        jButtonAbout.setText("About");
        jButtonAbout.addActionListener(evt -> jButtonAboutActionPerformed(evt));

        jButtonExit.setIcon(IconManager.loadIcon(IconManager.IconCategory.GENERAL, "Stop", 16, 16));
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(evt -> jButtonExitActionPerformed(evt));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAbout, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExit, GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonAbout)
                                .addComponent(jButtonExit))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jCheckBoxWindow)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCheckBoxTrayicon)))
                                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCheckBoxWindow)
                                        .addComponent(jCheckBoxTrayicon))
                                .addContainerGap(12, Short.MAX_VALUE))
        );
    }

    private void jButtonStartStopActionPerformed(java.awt.event.ActionEvent evt) {
        if (Server.isRunning())
            Server.Stop();
        else
            Server.Start();

        updateStatus();
    }

    private void jButtonViewersActionPerformed(java.awt.event.ActionEvent evt) {
        if (isServerRunning())
            ActiveConnectionsGUI.main(null);
    }

    private void jButtonConfigActionPerformed(java.awt.event.ActionEvent evt) {
        ConfigGUI.main(null);
    }

    private void jButtonAboutActionPerformed(java.awt.event.ActionEvent evt) {
        AboutGUI.main(null);
    }

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {
        if (JOptionPane.showConfirmDialog(this, "Exit application ?", "Confirm Dialog",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
            Main.exit();
    }

    private void jMenuItemSendFilesActionPerformed(java.awt.event.ActionEvent evt) {
        if (isServerRunning())
            if (Server.SendClipboardFileList() == 0) {
                JOptionPane.showMessageDialog(null, "No file in clipboard !!",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
            }
    }

    private void jMenuItemReceiveFilesActionPerformed(java.awt.event.ActionEvent evt) {
        if (isServerRunning())
            Server.setUploadingFolder();
    }

    private void jButtonFileTransActionPerformed(java.awt.event.ActionEvent evt) {
        jPopupMenuFileTranfer.show(jButtonFileTrans, 15, 15);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        ConnectionDialog.main(null);
    }

    private void jCheckBoxTrayiconActionPerformed(java.awt.event.ActionEvent evt) {
        Config.Systray_disabled = jCheckBoxTrayicon.isSelected();
        Config.storeConfiguration();

        if (!SysTray.isSupported()) {
            JOptionPane.showMessageDialog(this, "Systray not supported !!", "Info",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Config.Systray_disabled) {
            if (SysTray.isEnabled())
                SysTray.Hide();
        }
        else {
            if (!SysTray.isEnabled())
                SysTray.Show();
        }
    }

    private void jCheckBoxWindowActionPerformed(java.awt.event.ActionEvent evt) {
        Config.GUI_disabled = jCheckBoxWindow.isSelected();
        Config.storeConfiguration();
    }

    public static boolean isServerRunning() {
        boolean bool = Server.isRunning();
        if (!bool)
            JOptionPane.showMessageDialog(null,
                    "Server is not running !!",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        return bool;
    }

    public void updateStatus() {
        if (Server.isRunning()) {
            jTextAreaStatus.setText(Server.getStatus());
            jButtonStartStop.setText("Stop");
            jButtonStartStop.setIcon(IconManager.loadIcon(IconManager.IconCategory.MEDIA, "Stop", 16, 16));
        }
        else {
            if (Server.isIdle())
                jTextAreaStatus.setText("Idle.");
            else
                jTextAreaStatus.setText("Stopped.");
            jButtonStartStop.setText("Start");
            jButtonStartStop.setIcon(IconManager.loadIcon(IconManager.IconCategory.MEDIA, "Play", 16, 16));
        }
    }

    // Variables declaration
    private JButton jButton1;
    private JButton jButtonAbout;
    private JButton jButtonConfig;
    private JButton jButtonExit;
    private JButton jButtonFileTrans;
    private JButton jButtonStartStop;
    private JButton jButtonViewers;
    private JCheckBox jCheckBoxTrayicon;
    private JCheckBox jCheckBoxWindow;
    private JMenuItem jMenuItemReceiveFiles;
    private JMenuItem jMenuItemSendFiles;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPopupMenu jPopupMenuFileTranfer;
    private JScrollPane jScrollPane1;
    private JTextArea jTextAreaStatus;
}
