/**
 * Project Looking Glass
 *
 * Copyright (c) 2026, Jean-Francois Landreville, All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 */
package org.jdesktop.lg3d.apps.messenger;

/**
 * An immutable, protocol-neutral chat event delivered by a
 * {@link MessengerProtocol} to its {@link ProtocolListener}. Every backend
 * (the native IRC client, or any future plugin) normalises its wire traffic
 * into this one value type, so the UI never has to know which protocol a
 * message came from.
 *
 * <p>{@code from} is the sender's display identity (an IRC nick, a JID, a
 * phone number) or {@code null} for server/system events. {@code target} is the
 * conversation the event belongs to (a channel such as {@code #lg3d} or a peer
 * nick). {@code text} is the already-decoded, display-ready body.</p>
 */
public final class ChatMessage {

    /** The kind of chat event; drives how the UI renders and filters it. */
    public enum Kind {
        /** A normal chat message. */
        PRIVMSG,
        /** A {@code /me} action. */
        ACTION,
        /** A server/notice message (not user chat). */
        NOTICE,
        /** A local system/status line generated by the client itself. */
        SYSTEM,
        /** Someone joined a channel. */
        JOIN,
        /** Someone left a channel. */
        PART,
        /** Someone quit the network. */
        QUIT,
        /** Someone changed their nickname. */
        NICK,
        /** A channel topic changed. */
        TOPIC,
        /** An error reported by the server or the connection. */
        ERROR
    }

    private final String from;
    private final String target;
    private final String text;
    private final Kind kind;
    private final long epochMs;

    public ChatMessage(String from, String target, String text, Kind kind) {
        this(from, target, text, kind, System.currentTimeMillis());
    }

    public ChatMessage(String from, String target, String text, Kind kind, long epochMs) {
        this.from = (from == null) ? "" : from;
        this.target = (target == null) ? "" : target;
        this.text = (text == null) ? "" : text;
        this.kind = (kind == null) ? Kind.SYSTEM : kind;
        this.epochMs = epochMs;
    }

    /** Convenience factory for a local, client-generated status line. */
    public static ChatMessage system(String text) {
        return new ChatMessage(null, "", text, Kind.SYSTEM);
    }

    /** Convenience factory for an error line. */
    public static ChatMessage error(String text) {
        return new ChatMessage(null, "", text, Kind.ERROR);
    }

    public String getFrom() { return from; }
    public String getTarget() { return target; }
    public String getText() { return text; }
    public Kind getKind() { return kind; }
    public long getEpochMs() { return epochMs; }

    /** True if this event is user-facing chat rather than presence/system noise. */
    public boolean isChat() {
        return kind == Kind.PRIVMSG || kind == Kind.ACTION || kind == Kind.NOTICE;
    }

    /** True for presence/membership events (join, part, quit, nick, topic). */
    public boolean isPresence() {
        return kind == Kind.JOIN || kind == Kind.PART || kind == Kind.QUIT
                || kind == Kind.NICK || kind == Kind.TOPIC;
    }

    @Override
    public String toString() {
        return kind + (from.isEmpty() ? "" : " " + from) + " -> " + target + ": " + text;
    }
}
