/**
 * Project Looking Glass
 *
 * Copyright (c) 2026, Jean-Francois Landreville, All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 */
package com.protonmail.landrevillejf.swingide.update;

import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * Resolves the version of the running IDE.
 * <p>
 * The version is read from the {@code version.properties} resource generated by
 * the Gradle build ({@code generateVersionFile}) and can be forced with the
 * {@code lg3d.version} system property, which is handy for tests and for
 * custom launchers that do not embed the resource.
 * </p>
 */
@Slf4j
public final class ApplicationVersion {

    /** System property used to force the reported version. */
    public static final String VERSION_PROPERTY = "lg3d.version";

    /** Classpath resource generated by the Gradle build. */
    public static final String VERSION_RESOURCE = "/version.properties";

    private static final String VERSION_KEY = "app.version";
    private static final String BUILD_TIMESTAMP_KEY = "build.timestamp";

    /** Value reported when the version cannot be resolved. */
    public static final String UNKNOWN_VERSION = "0.0.0";

    private static final Properties VERSION_PROPERTIES = loadVersionProperties();

    private ApplicationVersion() {
        // Utility class
    }

    /**
     * Returns the version of the running IDE.
     *
     * @return the forced version, the packaged version or {@link #UNKNOWN_VERSION}
     */
    public static String current() {
        String forced = System.getProperty(VERSION_PROPERTY);
        if (forced != null && !forced.isBlank()) {
            return forced.trim();
        }

        String packaged = VERSION_PROPERTIES.getProperty(VERSION_KEY);
        if (packaged != null && !packaged.isBlank()) {
            return packaged.trim();
        }

        log.debug("No version could be resolved, reporting {}", UNKNOWN_VERSION);
        return UNKNOWN_VERSION;
    }

    /**
     * Returns the build timestamp packaged with the application.
     *
     * @return the build timestamp, or {@code null} when it is unknown
     */
    public static String buildTimestamp() {
        String timestamp = VERSION_PROPERTIES.getProperty(BUILD_TIMESTAMP_KEY);
        return timestamp != null && !timestamp.isBlank() ? timestamp.trim() : null;
    }

    private static Properties loadVersionProperties() {
        Properties properties = new Properties();
        try (InputStream in = ApplicationVersion.class.getResourceAsStream(VERSION_RESOURCE)) {
            if (in == null) {
                log.debug("{} not found on the classpath", VERSION_RESOURCE);
                return properties;
            }
            properties.load(in);
        } catch (IOException e) {
            log.warn("Could not read {}: {}", VERSION_RESOURCE, e.getMessage());
        }
        return properties;
    }
}
